[package]
name= "leetcode-practice"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "coin_change"
harness = false

[dependencies]
plotters = "0.3.7"
